### ISSUE TITLE
New shopping basket parameters from Wirecard

### ISSUE THREAD

**Issue by Trimnosh** [jch-wtag/solidus_wirecard_checkout_page#1]
Wirecard has recently updated the request parameters for the shopping basket data. Is an update planned?

**Comment by jch-wtag** [comment]
Thank you. Could you give me the link about these changing?

**Comment by Trimnosh** [comment]
Correction: The changes do not apply to the plugin since the shopping basket is not implemented. But thanks for the quick reply!

**Comment by jch-wtag** [comment]
@Trimnosh Thank you too for your clarification.
